# Generated by Django 5.1.5 on 2025-01-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_tourpackage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='Travel.flight'),
        ),
    ]
