# Generated by Django 5.1.5 on 2025-01-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_tourpackage_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='flights',
        ),
    ]
