# Generated by Django 5.1.5 on 2025-01-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PassportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('issuing_country', models.CharField(max_length=100)),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='passport_scans/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Travel.passenger')),
            ],
            options={
                'verbose_name_plural': 'Passport Details',
            },
        ),
    ]
