# Generated by Django 5.1.5 on 2025-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0009_packinglist_packingitem_packingpreferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
